RDMP-70 Change made to cause view stack trace to appear only when popup is an exception
HicServices/RDMP pull request #1810
Opened 2024-04-24 11:09 UTC by JBaird00183

[ticket](https://hicservices.atlassian.net/browse/RDMP-70)

When a popup appears that is generated by an exception the view stack trace button is present, otherwise the popup does not show this button.

Tested with 2 popups but will require more thorough testing in case any of the other applicable themes might require the view stack trace button for any reason.

2024-04-29 10:53 UTC, JFriel approved these changes

2024-04-30 07:22 UTC, JFriel requested changes
LGTM!
Add a note to the 8.1.5 changelog and you're good to merge

2024-05-08 09:15 UTC, JBaird00183 commented
Develop merged back into the branch, should be good to go now!

2024-05-14 07:37 UTC, JFriel approved these changes

2024-05-14 08:06 UTC, merged